### ISSUE TITLE
libwdsp.so: undefined reference to

### ISSUE THREAD

**Issue by karpenkoby** [g0orx/wdsp#11]
Hi, the build works fine, but when building another package, for example linhpsdr, the following happens:

gcc -o linhpsdr main.o css.o audio.o version.o discovered.o discovery.o protocol1_discovery.o protocol2_discovery.o property.o mode.o filter.o band.o radio.o receiver.o transmitter.o vfo.o meter.o rx_panadapter.o tx_panadapter.o mic_level.o mic_gain.o drive_level.o wideband_panadapter.o wideband_waterfall.o waterfall.o protocol1.o protocol2.o radio_dialog.o receiver_dialog.o transmitter_dialog.o pa_dialog.o eer_dialog.o wideband_dialog.o about_dialog.o button_text.o wideband.o vox.o ext.o configure_dialog.o bookmark_dialog.o puresignal_dialog.o oc_dialog.o xvtr_dialog.o frequency.o error_handler.o radio_info.o rigctl.o bpsk.o subrx.o soapy_discovery.o soapy_protocol.o  alsa_midi.o midi2.o midi3.o midi_dialog.o  -lrt -lm -lpthread -lwdsp `pkg-config --libs gtk+-3.0` -lasound -lpulse-simple -lpulse -lpulse-mainloop-glib -lsoundio -lSoapySDR   -lasound

/usr/bin/ld: /usr/local/lib/libwdsp.so: undefined reference to `pdisp'
/usr/bin/ld: /usr/local/lib/libwdsp.so: undefined reference to `txa'
/usr/bin/ld: /usr/local/lib/libwdsp.so: undefined reference to `ch'
/usr/bin/ld: /usr/local/lib/libwdsp.so: undefined reference to `pdexp'
/usr/bin/ld: /usr/local/lib/libwdsp.so: undefined reference to `rxa'
collect2: error: ld returned 1 exit status

Thank you!

gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/10.1.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++,d --with-isl --with-linker-hash-style=gnu --with-system-zlib --enable-__cxa_atexit --enable-cet=auto --enable-checking=release --enable-clocale=gnu --enable-default-pie --enable-default-ssp --enable-gnu-indirect-function --enable-gnu-unique-object --enable-install-libiberty --enable-linker-build-id --enable-lto --enable-multilib --enable-plugin --enable-shared --enable-threads=posix --disable-libssp --disable-libstdcxx-pch --disable-libunwind-exceptions --disable-werror gdc_include_dir=/usr/include/dlang/gdc
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.1.0 (GCC)

**Comment by g0orx** [comment]
Latest push fixes this. I should have installed wdsp and compiled others.

-- John

**Comment by karpenkoby** [comment]
OK! Thank you! It works!
