### ISSUE TITLE
fprintf causing constant stream of text on command line

### ISSUE THREAD

**Issue by m5evt** [g0orx/wdsp#22]
Confirmed in linHPSDR and piHPSDR. See [here](https://github.com/g0orx/wdsp/commit/e277f0c093e25eb55d27ae191cdffc29b59eec29#r63974419) for code. Is this purely debugging code left in?

**Comment by pa3gsb** [comment]
My bad. Will make a pull request.
In the process of making a java backend...there was an issue which i reported to Warren... i had to add debug statements to get an idea of the origin of the problem.

**Comment by m5evt** [comment]
Closed by PR #23
